language: generic
include:
- os: linux
addons:
  apt:
    update: true
sudo: required
git:
  depth: 22
before_script:
- sudo apt-get install devscripts debhelper libfile-fcntllock-perl
script:
- chmod +x debuild.sh
- "./debuild.sh |& tee log.txt"
after_script:
- bash ./scripts/deploy.sh
before_deploy:
- export logo_package="`echo plymouth-theme-meilix-logo_*_all.deb`"
- export text_package="`echo plymouth-theme-meilix-text_*_all.deb`"
- export login_package="`echo sddm-theme-meilix_*_all.deb`"
- export theme_package="`echo meilix-default-theme_*_all.deb`"
- cat plymouth-theme-meilix-logo_*_all.deb > "/home/travis/${logo_package}"
- cat plymouth-theme-meilix-text_*_all.deb > "/home/travis/${text_package}"
- cat sddm-theme-meilix_*_all.deb > "/home/travis/${login_package}"
- cp log.txt /home/travis/log.txt
notifications: 
slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
deploy:
  provider: releases
  api_key:
    secure: YrzxdmrlU3QoNPgNZMs0Rfxxks7ZPIp8Vw+X7xHWNV+e13N40LIM4WIICcwgp6y89jwGIcW3llVcpeuy/1MPtYrd4ygz25FUQRCcUcOeHGCKexW8o7zKFWgz/MG9GYHha1e6UbI8fKcPfjTgZ+yxqIcvaYgiMx9BDec00hA9uj+jgdte2h52cRFZtMGCY2DEa8UiUbKf389Q8MRXF+JbhgXJIorcbJfSvdtU5kB0ph39qeHU5VPJ5XQ7leD/riTwWus5hnWob4I+H/Uvm+iBjeEzkn2h8kjfvNwplnMoSFrg/29BFu870yKHcCHA9RrT+C+wxAyEq6MmygcMEIN4UJUkxEjwEhItmaIJnlW2i9EqTnBsW9NIAoE3G/9WlUFDIxYgXv/tAHow1p7DYAajRT6bol7ivdAwDLQi7mnW88VrFpnrKU1+5HDAvW7YI9Rzot/uZ+kGeScicQP6p3Mvacpy1dH6caB9fQ92dr9zKkDO3ktKIlxWvRw1SmiqPV059eOCMohZQWDEoxnosJB8L+3AJn0IAnCB+UsrTr72aTMHex6z7aZueErFvIKU3jizyUTetdkadmU9klwIZ88hKFR+DzQ45v83jAOxz+FRxRE2tD7E9c1xxB0JB8lygtGu8FQaMUSgAj9jfdkHDUTAejDbWHE4odAyEhn+1ESE2L4=
  file: ./meilix-default-dark-theme_1.0-2_all.deb
  on:
    repo: pranav1698/meilix-artwork
    branch: theme-test
